[package]

name = "messin"
version = "0.0.1"
authors = ["riley"]

[dependencies]
time = "*"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin.git"
