[package]

name = "messin"
version = "0.0.1"
authors = ["riley"]

[dependencies]
time = "*"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2.git"
